### ISSUE TITLE
hoodie@11.0.0 requests hoodie-server@11.0.0 that requests hoodie@^2.1.1 what?

### ISSUE THREAD

**Issue by rogeriochaves** [hoodiehq/hoodie#434]
I can't install hoodie on npm 3.3.10 because of that, my package json has only one dependency:

``` json
"dependencies": {
    "hoodie": "^11.0.0"
}
```

and it throws

`npm WARN EPEERINVALID hoodie-server@11.0.0 requires a peer of hoodie@^2.1.1 but none was installed.`

I noticed that hoodie-server@12.0.0 doesn't have this problem, could we make hoodie depend on that?

**Comment by gr2m** [comment]
That should be resolved now, I'll look into it :)

**Comment by gr2m** [comment]
starter PR at #438

**Comment by prenaudin** [comment]
Still having the same issue when running `npm install --save hoodie@next`, any updates on this PR #438 ? 🐕😺

**Comment by gr2m** [comment]
I'm all over this right now, I hope I got something by tomorrow. If not try to install `hoodie` from the `tent` branch

**Comment by prenaudin** [comment]
Great News, still having issues on tent branch. I'll wait, I'm here if you need someone to test 😉

**Comment by gr2m** [comment]
fresh from the press: https://github.com/hoodiehq/my-first-hoodie/tree/something-tracker#local-setup-to-test-new-hoodie

note that this is still pretty buggy. But if you are interested in getting involved, there won’t be a better time than today :) We put a ton of efforts to making the new architecture modular, and make each (sub) module well tested, documented, and easy to contribute to. 

Ping me for any questions. I’ll also hang out in http://hood.ie/chat/ most of European day time
